site_name: A Focused Traffic Engineer

theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs 
    - navigation.sections

plugins:
  - search:
      enabled: false    # remove search box

nav:
  - Home: index.md
  - Articles: blog.md
  - About: about.md

extra:
  generator: false
copyright: "Copyright &copy; 2026 George Zhang"

extra_css:
  - stylesheets/extra.css

