site_name: A Focused Traffic Engineer

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs 
    - navigation.sections
    - toc.integrate


plugins:
  - search:
      enabled: false    # remove search box

nav:
  - Home: index.md
  - Blog:
    - Overview: blog.md
    - My First Post: blog/posts/second-post.md
    - Another Post: blog/posts/first-post.md
  - About: about.md

extra:
  generator: false
copyright: "Copyright &copy; 2026 George Zhang"

extra_css:
  - stylesheets/extra.css